name: CLI build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup dotnet environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "2.2.401" # SDK Version to use.
      - name: Build app
        run: dotnet build src/AHK.sln
        env:
          # Work around https://github.com/actions/setup-dotnet/issues/29
          DOTNET_ROOT: /opt/hostedtoolcache/dncs/2.2.401/x64
      - name: Test
        run: dotnet test src/AHK.sln
        env:
          # Work around https://github.com/actions/setup-dotnet/issues/29
          DOTNET_ROOT: /opt/hostedtoolcache/dncs/2.2.401/x64
