name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.407"

      - name: dotnet build
        working-directory: src
        run: dotnet build

      - name: dotnet test
        working-directory: src
        run: dotnet test
